jsonplaceholder_callout/setup/objects/JSONPlaceholderUser__c/JSONPlaceholderUser__c.object-meta.xml
<CustomObject>
    <label>JSON Placeholder User</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JSON Placeholder Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject> 

jsonplaceholder_callout/setup/objects/JSONPlaceholderUser__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField> 

jsonplaceholder_callout/setup/objects/JSONPlaceholderUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

jsonplaceholder_callout/setup/objects/JSONPlaceholderUser__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField> 

jsonplaceholder_callout/setup/objects/JSONPlaceholderUser__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField> 

jsonplaceholder_callout/setup/objects/JSONPlaceholderUser__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField> 

jsonplaceholder_callout/setup/objects/JSONPlaceholderUser__c/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <label>Website</label>
    <type>Url</type>
</CustomField> 

jsonplaceholder_callout/classes/JSONPlaceholderUserTriggerHelper.cls
public class JSONPlaceholderUserTriggerHelper {

    public static JSONPlaceholderAPI.JSONPlaceholderUserDTO buildUserDTO(JSONPlaceholderUser__c user) {
        JSONPlaceholderAPI.JSONPlaceholderUserDTO userDTO = new JSONPlaceholderAPI.JSONPlaceholderUserDTO();
        userDTO.id = (Integer) user.ExternalId__c;
        userDTO.name = user.Name__c;
        userDTO.username = user.Username__c;
        userDTO.email = user.Email__c;
        userDTO.phone = user.Phone__c;
        userDTO.website = user.Website__c;
        return userDTO;
    }

}